[pyrefly]
ignore = ["**/_pyrefly_virtual_/**"]
search_paths = [
  ".",
  ".venv/Lib/site-packages"
]

[tool.pyrefly]
ignore = ["**/_pyrefly_virtual_/**"]
search_paths = [
  ".",
  ".venv/Lib/site-packages"
]

